[project]
name = "datajam-cyberabad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anywidget>=0.11.0",
    "duckdb>=1.5.5",
    "firecrawl-py>=4.43.0",
    "folium>=0.20.0",
    "geopandas>=1.1.4",
    "h3>=4.5.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "networkx>=3.6.1",
    "numpy>=2.5.3",
    "osmnx>=2.1.1",
    "pandas>=3.0.6",
    "plotly>=7.1.0",
    "pydeck>=0.9.3",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
]
